package gr.aueb.cf.medicalappointmentmanager.model;

public enum Speciality {
    CARDIOLOGY,
    DERMATOLOGY,
    NEUROLOGY,
    PEDIATRICS,
    ONCOLOGY,
    ORTHOPEDICS,
    GASTROENTEROLOGY,
    ENDOCRINOLOGY,
    PSYCHIATRY,
    OPHTHALMOLOGY,
    UROLOGY,
    GYNECOLOGY,
    PULMONOLOGY,
    RHEUMATOLOGY,
    INFECTIOUS_DISEASE,
    HEMATOLOGY,
    NEPHROLOGY,
    ALLERGY_IMMUNOLOGY,
    ANESTHESIOLOGY,
    PLASTIC_SURGERY
}
